# Eureka Configuration
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
eureka.instance.prefer-ip-address: true
eureka.instance.hostname: localhost


# actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"


# zipkin config
management.tracing.sampling.probability: 1.0
spring.zipkin.baseUrl: http://localhost:9411


logging:
  config: classpath:logback-spring.xml
